package at.fhv.puzzle2.server.database;

import java.sql.*;

public class DatabaseConnection {
    private final Connection _connection;
    private final Object _lock = new Object();

    public DatabaseConnection(Connection connection) {
        _connection = connection;
    }

    public ResultSet executeQuery(String query) {
        synchronized (_lock) {
            Statement statement = null;
            try {
                statement = _connection.createStatement();
                return statement.executeQuery(query);
            } catch (SQLException e) {
                throw new UncheckedSQLException(e);
            }
        }
    }

    /**
     * Returns the generated key
     * @param query String
     * @return Returns the generated key
     */
    public int executeSingleUpdateOrInsert(String query) {
        synchronized (_lock) {
            try {
                Statement statement = _connection.createStatement();
                return statement.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
            } catch(SQLException e) {
                throw new UncheckedSQLException(e);
            }
        }
    }

    public PreparedStatement createPreparedStatement(String query, int autogeneratedKeys) {
        try {
            return _connection.prepareStatement(query, autogeneratedKeys);
        } catch(SQLException e) {
            throw new UncheckedSQLException(e);
        }
    }

    public void close() {
        try {
            _connection.close();
        } catch(SQLException e) {
            //We wont do anything here, we wanted to close it anyway
        }
    }
}
