package at.fhv.puzzle2.server.database;

import java.sql.*;

public class DatabaseConnection {
    private Connection _connection;
    private final Object _lock = new Object();

    public DatabaseConnection(Connection connection) {
        _connection = connection;
    }

    public ResultSet executeQuery(String query) throws SQLException {
        synchronized (_lock) {
            Statement statement = _connection.createStatement();
            return statement.executeQuery(query);
        }
    }

    /**
     * Returns the generated key
     * @param query String
     * @return Returns the generated key
     * @throws SQLException
     */
    public int executeSingleUpdateOrInsert(String query) throws SQLException {
        synchronized (_lock) {
            Statement statement = _connection.createStatement();
            return statement.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
        }
    }

    public PreparedStatement createPreparedStatement(String query, int autogeneratedKeys) throws SQLException {
        synchronized (_lock) {
            return _connection.prepareStatement(query, autogeneratedKeys);
        }
    }

    public PreparedStatement createPreparedStatement(String query) throws SQLException {
        return createPreparedStatement(query, Statement.NO_GENERATED_KEYS);
    }
}
