[server]
broadcast_message = "PUZZLE2"
loop_time = 500 #Zeit eines Gameloops in Millisekunden

[database]
host = "localhost"
port = 3306 #Default mysql port ist 3306
database = "puzzle2" # Datenbank, welche verwendet werden soll
user = "root"
password = "root"

[game]
team_names = ["Epic Team", "DAUs", "Die Schürzenjäger", "Ghetto Gangsters"]

#Logger wird noch nicht ausgelesen, kommt noch
[logger]
#Mögliche Loglevel sind: Error, Warning, Info, Debug, Trace
logLevel = "Trace"
formatter = "SimpleFormatter"

[[logger.sink]]
sink = "Console"

[[logger.sink]]
sink = "SimpleFile"
parameters = ["puzzle2.log"]
